hazus2ind.hazus_codes = {'RES1',...
'RES2',...
'RES3',...
'RES4',...
'RES5',...
'RES6',...
'COM1',...
'COM2',...
'COM3',...
'COM4',...
'COM5',...
'COM6',...
'COM7',...
'COM8',...
'COM9',...
'COM10',...
'IND1',...
'IND2',...
'IND3',...
'IND4',...
'IND5',...
'IND6',...
'AGR1',...
'REL1',...
'GOV1',...
'GOV2',...
'EDU1',...
'EDU2'}

hazus2ind.ind_code = {'Agriculture, forestry, fishing, and hunting',...
    'Mining',...
    'Utilities',...
    'Construction',...
    'Manufacturing',...
    'Wholesale trade',...
    'Retail trade',...
    'Transportation and warehousing',...
    'Information',...
    'Finance, insurance, real estate, rental, and leasing',...
    'Professional and business services',...
    'Educational services, health care, and social assistance',...
    'Arts, entertainment, recreation, accommodation, and food services',...
    'Other services, except government',...
  'Government'};%
%'Household'};